name: CI

on:
  schedule:
    - cron: '0 0 * * *'
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - DBAL ${{ matrix.dbal }}

    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4']
        laravel: ['10', '11', '12']
        dbal: ['^2.10.1', '^3', '^4']
        exclude:
          - php: '8.4'
            laravel: '10'

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: phpunit, git

      - name: Install Composer dependencies
        run: rm -f composer.lock

      - name: Install Laravel ${{ matrix.laravel }} and Doctrine DBAL ${{ matrix.dbal }}
        run: |
          composer require --no-update --no-scripts --no-plugins \
            illuminate/config:^${{ matrix.laravel }} \
            illuminate/contracts:^${{ matrix.laravel }} \
            illuminate/console:^${{ matrix.laravel }} \
            doctrine/dbal:${{ matrix.dbal }}

      - name: Update dependencies
        run: composer update --no-interaction --prefer-dist

      - name: PHPUnit
        run: vendor/bin/phpunit
